In [1]:
import json
import pandas as pd

# **Extracted Data**

## **Food Id name Mapping**

In [2]:
food_ids_path = r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\tables\food_ids.json"

with open(food_ids_path, "r", encoding="utf-8") as f:
    data = json.load(f)

In [3]:
data[:3]

[{'food_id': 'F0001',
  'food_name': '_lactobacillus spicheri_ g2',
  'aliases': ['_lactobacillus spicheri_ g2']},
 {'food_id': 'F0002', 'food_name': '_namsing_', 'aliases': ['_namsing_']},
 {'food_id': 'F0003',
  'food_name': 'african or european traditional cultured milks',
  'aliases': ['african or european traditional cultured milks']}]

In [4]:
len(data)

83

In [5]:
food_ids_df = pd.DataFrame(data)
food_ids_df

,food_id,food_name,aliases
0,F0001,_lactobacillus spicheri_ g2,[_lactobacillus spicheri_ g2]
1,F0002,_namsing_,[_namsing_]
2,F0003,african or european traditional cultured milks,[african or european traditional cultured milks]
3,F0004,akhuni (fermented soya beans),[akhuni (fermented soya beans)]
4,F0005,akhuni/axone,[akhuni/axone]
...,...,...,...
78,F0079,utonga-kupsu,[utonga-kupsu]
79,F0080,wet/pulp/smoked,[wet/pulp/smoked]
80,F0081,zao,[zao]
81,F0082,ziang dui,[ziang dui]
82,F0083,ziang sang,[ziang sang]

## **Table 1**

In [6]:
t1 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\tables\table1.json")
t1

,food_id,food_name,category,type,ethnic_group,source_pdf,source_pdfs,evidence,conflicts,evidence_verification
0,F0001,_lactobacillus spicheri_ g2,Fermented Vegetable,Solid Fermented Food,None,Indigenous fermented foods of Northeast India ...,[Indigenous fermented foods of Northeast India...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...,[],"{'food_name': 'exact_in_discovery_chunk', 'fie..."
1,F0002,_namsing_,Fermented Fish,Solid Fermented Food,Mising community of Assam,Indigenous fermented foods of Northeast India ...,[Indigenous fermented foods of Northeast India...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...,[],"{'food_name': 'exact_in_discovery_chunk', 'fie..."
2,F0003,african or european traditional cultured milks,Fermented Dairy,Liquid Fermented Food,Northeast India,Ethnic fermentation secrets of Northeast India...,[Ethnic fermentation secrets of Northeast Indi...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...,[],"{'food_name': 'exact_in_discovery_chunk', 'fie..."
3,F0004,akhuni (fermented soya beans),Fermented Vegetable,Solid Fermented Food,Sümi tribe,BambooShootinourBlood.pdf,[BambooShootinourBlood.pdf],[{'chunk_id': 'BambooShootinourBlood_c00014_ff...,[],"{'food_name': 'exact_in_discovery_chunk', 'fie..."
4,F0005,akhuni/axone,Fermented Vegetable,Solid Fermented Food,Naga,BambooShootinourBlood.pdf,"[BambooShootinourBlood.pdf, Ethnic fermentatio...",[{'chunk_id': 'BambooShootinourBlood_c00012_1d...,"[{'field': 'ethnic_group', 'existing': 'Naga',...","{'food_name': 'exact_in_discovery_chunk', 'fie..."
...,...,...,...,...,...,...,...,...,...,...
78,F0079,utonga-kupsu,Fermented Fish,Solid Fermented Food,None,Indigenous fermented foods of Northeast India ...,[Indigenous fermented foods of Northeast India...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...,[],"{'food_name': 'exact_in_discovery_chunk', 'fie..."
79,F0080,wet/pulp/smoked,Fermented Vegetable,Solid Fermented Food,Naga,BambooShootinourBlood.pdf,[BambooShootinourBlood.pdf],[{'chunk_id': 'BambooShootinourBlood_c00012_1d...,[],"{'food_name': 'exact_in_discovery_chunk', 'fie..."
80,F0081,zao,Fermented Beverage,Liquid Fermented Food,None,Metagenomic insights into traditional fermenta...,[Metagenomic insights into traditional ferment...,[{'chunk_id': 'Metagenomic_insights_into_tradi...,[],"{'food_name': 'exact_in_discovery_chunk', 'fie..."
81,F0082,ziang dui,Fermented Vegetable,Solid Fermented Food,None,Northeast India.pdf,[Northeast India.pdf],[{'chunk_id': 'Northeast_India_c00010_24a2beee...,[],"{'food_name': 'exact_in_discovery_chunk', 'fie..."
82,F0083,ziang sang,Fermented Vegetable,Solid Fermented Food,None,Northeast India.pdf,[Northeast India.pdf],[{'chunk_id': 'Northeast_India_c00010_24a2beee...,[],"{'food_name': 'exact_in_discovery_chunk', 'fie..."

In [7]:
len(t1['food_id'])

83

In [8]:
t1['category'].value_counts()

category
Fermented Vegetable        41
Fermented Fish             22
Fermented Beverage          9
Fermented Dairy             5
Solid Fermented Food        1
Fermented Fish Products     1
Fermented Soybean           1
Fermented Meat and Fish     1
Name: count, dtype: int64

In [9]:
t1['type'].value_counts()

type
Solid Fermented Food                65
Liquid Fermented Food               11
Non-alcoholic Fermented Beverage     3
Fermented Beverage                   1
Alcoholic Fermented Beverage         1
Name: count, dtype: int64

In [10]:
t1['ethnic_group'].value_counts()

ethnic_group
Northeast India                  25
Naga                              5
Garo tribe                        3
Mising community of Assam         1
Sümi tribe                        1
Barman community                  1
People of Northeast India         1
Assam                             1
Dimasa Kachari community          1
Thai                              1
Manipur                           1
Meiteilon                         1
Lotha Naga tribe of Nagaland      1
Arunachal Pradesh and Manipur     1
Name: count, dtype: int64

In [11]:
ethnic_group_col_val = t1['ethnic_group'].to_list()
ethnic_group_col_val = [ str(e).split(',') for e in ethnic_group_col_val]
ethnic_group = []

for e in ethnic_group_col_val:
    ethnic_group.extend(e)
ethnic_group = [ e.strip() for e in ethnic_group ]
ethnic_group,len(ethnic_group)

(['None',
  'Mising community of Assam',
  'Northeast India',
  'Sümi tribe',
  'Naga',
  'None',
  'None',
  'None',
  'Northeast India',
  'None',
  'None',
  'Barman community',
  'Northeast India',
  'People of Northeast India',
  'None',
  'None',
  'Assam',
  'Northeast India',
  'Northeast India',
  'Northeast India',
  'Northeast India',
  'None',
  'None',
  'Northeast India',
  'Naga',
  'Northeast India',
  'Northeast India',
  'Northeast India',
  'None',
  'None',
  'Northeast India',
  'Garo tribe',
  'None',
  'None',
  'None',
  'None',
  'Naga',
  'None',
  'None',
  'Dimasa Kachari community',
  'None',
  'None',
  'Northeast India',
  'None',
  'None',
  'None',
  'None',
  'Northeast India',
  'Northeast India',
  'Thai',
  'None',
  'None',
  'Northeast India',
  'None',
  'Northeast India',
  'None',
  'Garo tribe',
  'Naga',
  'Northeast India',
  'None',
  'Manipur',
  'Northeast India',
  'Northeast India',
  'None',
  'Northeast India',
  'Northeast India',
  'Garo tribe',
  'Northeast India',
  'Northeast India',
  'None',
  'Meiteilon',
  'Lotha Naga tribe of Nagaland',
  'None',
  'None',
  'None',
  'Northeast India',
  'None',
  'Arunachal Pradesh and Manipur',
  'None',
  'Naga',
  'None',
  'None',
  'None'],
 83)

In [12]:
ethnic_group_set = set(ethnic_group)
ethnic_group_set,len(ethnic_group_set)

({'Arunachal Pradesh and Manipur',
  'Assam',
  'Barman community',
  'Dimasa Kachari community',
  'Garo tribe',
  'Lotha Naga tribe of Nagaland',
  'Manipur',
  'Meiteilon',
  'Mising community of Assam',
  'Naga',
  'None',
  'Northeast India',
  'People of Northeast India',
  'Sümi tribe',
  'Thai'},
 15)

## **Table 2**

In [13]:
t2 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\tables\table2.json")
t2

,food_id,food_name,evidence_chunk_ids,raw_material,amount,preparation_method,evidence_verification,source_pdf,evidence
0,F0002,_namsing_,[Indigenous_fermented_foods_of_Northeast_India...,_Namsing_,NaN,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
1,F0003,african or european traditional cultured milks,[Ethnic_fermentation_secrets_of_Northeast_Indi...,LAByeast consortia or kefir grains,NaN,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
2,F0003,african or european traditional cultured milks,[Ethnic_fermentation_secrets_of_Northeast_Indi...,defined inoculum of _B. subtilis_ var. _natto_,NaN,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
3,F0004,akhuni (fermented soya beans),"[BambooShootinourBlood_c00014_ff4f1c86, Bamboo...",tender bamboo shoot,NaN,chopped and sealed in assigned jars,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00014_ff...
4,F0004,akhuni (fermented soya beans),[BambooShootinourBlood_c00022_3bb1b36f],akhuni (fermented soya beans),NaN,None,"{'status': 'verified_with_removed_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00022_3b...
...,...,...,...,...,...,...,...,...,...
84,F0076,traditional sausages,[Ethnic_fermentation_secrets_of_Northeast_Indi...,rice-based fermented beverages,NaN,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
85,F0077,tungrymbai,[Indigenous_fermented_foods_of_Northeast_India...,Tungrymbai,NaN,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
86,F0078,tungtap,[Indigenous_fermented_foods_of_Northeast_India...,Tungtap,NaN,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
87,F0078,tungtap,[Microbial_and_endogenous_origin_of_fibrinolyt...,phabou (P. sophore),NaN,"used for the production of ngari, shedal, tung...","{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
88,F0080,wet/pulp/smoked,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",fermented bamboo shoot (wet/pulp/smoked),NaN,any fresh bamboo shoot chopped and stored in a...,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...

In [15]:
t2['raw_material'].value_counts()

raw_material
fermented bamboo shoot                                 7
bamboo shoot                                           5
phabou (P. sophore)                                    4
fish                                                   3
Ngari                                                  3
fermented soya beans and some bamboo shoot             2
Shidal                                                 2
LAByeast consortia or kefir grains                     2
Hawaijar                                               2
humao                                                  2
Seedal                                                 2
phabou                                                 2
areca nut                                              2
fermented bamboo shoot (wet/pulp/smoked)               2
tender bamboo shoot                                    2
defined inoculum of _B. subtilis_ var. _natto_         2
native isolates                                        2
Bacillus                                               1
black and white mustard seeds                          1
mustard seeds                                          1
myul-chi-jeot-gal                                      1
miso                                                   1
Bacillus subtilis                                      1
Staphylococcus                                         1
Micrococcus                                            1
Puntius spp. and phasa fish (Setipinna phasa)          1
_Bacillus subtilis_ and _Staphylococcus nepalensis_    1
Sa-um                                                  1
brine                                                  1
starter systems                                        1
punti and phasa shidal                                 1
soya beans                                             1
Squid miso                                             1
thap                                                   1
rice-based fermented beverages                         1
Tungrymbai                                             1
Korean fermented fish Jeot-Gal                         1
_Namsing_                                              1
kimchi                                                 1
khalpi                                                 1
akhuni (fermented soya beans)                          1
anishi                                                 1
Chinese douchi                                         1
Bamboo shoots                                          1
_Aspergillus oryzae_ starters                          1
_Listeria_                                             1
_B. cereus_ toxins                                     1
fermented pork products                                1
fermented soybean                                      1
fermented fish                                         1
fish sauce                                             1
fish paste                                             1
goyang                                                 1
Staphylococci                                          1
Hentaak                                                1
Hentak                                                 1
Japanese shiokara                                      1
fresh bamboo shoot                                     1
Kapi                                                   1
Tungtap                                                1
Name: count, dtype: int64

## **Table 3**

In [34]:
t3 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\verification\verified\table3.json")
t3

,food_id,food_name,evidence_chunk_ids,state,district,ethnic_group,village,evidence_verification,source_pdf,evidence
0,F0002,_namsing_,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,Mising community of Assam,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
1,F0004,akhuni (fermented soya beans),"[BambooShootinourBlood_c00014_ff4f1c86, Bamboo...",None,NaN,Sümi tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00014_ff...
2,F0005,akhuni/axone,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Naga,Dimapur,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
3,F0006,anishi,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Khasis,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
4,F0006,anishi,[Northeast_India_c00003_ce27a60c],None,NaN,Northeast Indian women,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00003_ce27a60c...
5,F0010,baiya nigu,"[BambooShootinourBlood_c00028_5d7bb136, Bamboo...",None,NaN,Lotha Naga community,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00028_5d...
6,F0011,bamboo shoot,"[BambooShootinourBlood_c00005_7e25a3da, Bamboo...",None,NaN,Naga,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00005_7e...
7,F0012,barman community,"[BambooShootinourBlood_c00018_881965e5, Bamboo...",None,NaN,Barman community,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00018_88...
8,F0013,cheese,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
9,F0021,fermented foods,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
10,F0022,fermented mustard seeds,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Khasis,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
11,F0025,fermented yam leaves,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Khasis,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
12,F0025,fermented yam leaves,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Naga,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
13,F0026,fish paste,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,tribal communities of Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
14,F0027,fish sauce,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,tribal communities of Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
15,F0032,hentaak,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,Garo tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
16,F0037,inziangsang,"[Northeast_India_c00003_ce27a60c, Northeast_In...",None,NaN,Naga,Manipur and Nagaland,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00003_ce27a60c...
17,F0039,japanese shiokara,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,NaN,Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
18,F0040,judima,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,Dimasa Kachari community,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
19,F0040,judima,[Metagenomic_insights_into_traditional_ferment...,None,NaN,Dimasa Kachari,Judima,"{'status': 'verified_exact_or_normalized', 'fi...",Metagenomic insights into traditional fermenta...,[{'chunk_id': 'Metagenomic_insights_into_tradi...
20,F0041,kahudi/panitenga,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Khasis,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
21,F0044,khalpi,[Northeast_India_c00003_ce27a60c],None,NaN,Northeast Indian women,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00003_ce27a60c...
22,F0045,kharoli,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Khasis,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
23,F0048,kimchi,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
24,F0049,kombucha,[BambooShootinourBlood_c00023_b6a2b5b8],New Delhi,NaN,None,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00023_b6...
25,F0049,kombucha,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
26,F0054,moinapara,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,None,Moinapara village,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
27,F0054,moinapara,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,Karbi community,Kuki household in Karbi Anglong,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
28,F0055,mustard seeds,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,Assam and the surrounding Northeastern states,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
29,F0057,na.kam su.a,[Traditional_preparation_of_Na_kam_su_a_-_an_e...,None,NaN,Garo tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",Traditional preparation of Na kam su.a - an et...,[{'chunk_id': 'Traditional_preparation_of_Na_k...
30,F0058,naga,"[BambooShootinourBlood_c00028_5d7bb136, Bamboo...",None,NaN,Lotha Naga community,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00028_5d...
31,F0061,ngari,[Chemical_and_microbial_properties_of_shidal_a...,None,NaN,Manipur,None,"{'status': 'verified_exact_or_normalized', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
32,F0061,ngari,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,Garo tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
33,F0061,ngari,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,NaN,None,Ngari (fermented fish product of Manipur),"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
34,F0061,ngari,[Traditional_preparation_of_Na_kam_su_a_-_an_e...,None,NaN,Garo tribes,None,"{'status': 'verified_exact_or_normalized', 'fi...",Traditional preparation of Na kam su.a - an et...,[{'chunk_id': 'Traditional_preparation_of_Na_k...
35,F0065,salami,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,tribal communities of Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
36,F0067,seedal,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,Garo tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
37,F0067,seedal,[Indigenous_fermented_foods_of_Northeast_India...,Arunachal Pradesh,NaN,None,Manipur,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
38,F0068,shedal,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,NaN,None,Phabou (P. sophore),"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
39,F0069,shidal,[Chemical_and_microbial_properties_of_shidal_a...,None,NaN,Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
40,F0069,shidal,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,Garo tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
41,F0070,sinki,[Northeast_India_c00003_ce27a60c],None,NaN,Northeast Indian women,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00003_ce27a60c...
42,F0071,soidon,[Indigenous_fermented_foods_of_Northeast_India...,Nagaland,NaN,Naga,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
43,F0072,soya beans,"[BambooShootinourBlood_c00005_7e25a3da, Bamboo...",None,NaN,Lotha Naga tribe of Nagaland,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00005_7e...
44,F0075,thap,[Metagenomic_insights_into_traditional_ferment...,None,NaN,Karbi tribes,Hor Alank,"{'status': 'verified_exact_or_normalized', 'fi...",Metagenomic insights into traditional fermenta...,[{'chunk_id': 'Metagenomic_insights_into_tradi...
45,F0075,thap,[Metagenomic_insights_into_traditional_ferment...,None,NaN,Tea tribes,Haria,"{'status': 'verified_exact_or_normalized', 'fi...",Metagenomic insights into traditional fermenta...,[{'chunk_id': 'Metagenomic_insights_into_tradi...
46,F0076,traditional sausages,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,tribal communities of Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
47,F0078,tungtap,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,NaN,None,Tungtap,"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
48,F0082,ziang dui,[Northeast_India_c00010_24a2beee],None,NaN,Naga women,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
49,F0083,ziang sang,[Northeast_India_c00010_24a2beee],None,NaN,Naga women,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...

In [17]:
t3['state'].value_counts()

state
New Delhi            1
Arunachal Pradesh    1
Nagaland             1
Name: count, dtype: int64

In [18]:
t3['district'].value_counts()

Series([], Name: count, dtype: int64)

In [19]:
t3['ethnic_group'].value_counts()

ethnic_group
Northeast India                                  6
Naga                                             5
Khasis                                           5
Garo tribe                                       5
tribal communities of Northeast India            4
Northeast Indian women                           3
Naga women                                       2
Lotha Naga community                             2
Manipur                                          1
Tea tribes                                       1
Karbi tribes                                     1
Lotha Naga tribe of Nagaland                     1
Garo tribes                                      1
Mising community of Assam                        1
Assam and the surrounding Northeastern states    1
Karbi community                                  1
Dimasa Kachari                                   1
Sümi tribe                                       1
Barman community                                 1
Dimasa Kachari community                         1
Name: count, dtype: int64

In [20]:
t3['village'].value_counts()

village
Dimapur                                      1
Manipur and Nagaland                         1
Judima                                       1
Moinapara village                            1
Kuki household in Karbi Anglong              1
Ngari (fermented fish product of Manipur)    1
Manipur                                      1
Phabou (P. sophore)                          1
Hor Alank                                    1
Haria                                        1
Tungtap                                      1
Name: count, dtype: int64

In [35]:
len(t3)

50

## **Table 4: Nutrition**

In [21]:
t4 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\tables\table4.json")
t4

,food_id,food_name,evidence_chunk_ids,category,parameter,value,unit,evidence_verification,source_pdf,evidence
0,F0018,fermented bamboo shoot,"[BambooShootinourBlood_c00015_57ed4e30, Bamboo...",Proximate Composition,sour,strong,,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00015_57...
1,F0018,fermented bamboo shoot,[BambooShootinourBlood_c00015_57ed4e30],Proximate Composition,sweetness,strong,,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00015_57...
2,F0018,fermented bamboo shoot,[BambooShootinourBlood_c00015_57ed4e30],Proximate Composition,sour,way too strong for me,,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00015_57...
3,F0057,na.kam su.a,[Traditional_preparation_of_Na_kam_su_a_-_an_e...,Proximate Composition,moisture content,36.82%,None,{'status': 'verified_with_derived_and_removed_...,Traditional preparation of Na kam su.a - an et...,[{'chunk_id': 'Traditional_preparation_of_Na_k...

In [22]:
t4['category'].value_counts()

category
Proximate Composition    4
Name: count, dtype: int64

In [23]:
t4['parameter'].value_counts()

parameter
sour                2
sweetness           1
moisture content    1
Name: count, dtype: int64

## **Table 5**

In [24]:
t5 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\tables\table5.json")
t5.head()

Empty DataFrame
Columns: []
Index: []

In [25]:
t5['moisture'].value_counts()

KeyError: 'moisture'

In [26]:
t5['ash'].value_counts()

KeyError: 'ash'

## **Table 6**

In [25]:
t6 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\tables\table6.json")
t6

,food_id,food_name,evidence_chunk_ids,taxonomy_level,taxonomy_name,evidence_verification,source_pdf,evidence
0,F0005,akhuni/axone,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",species,axone,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
1,F0005,akhuni/axone,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Leuconostoc_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
2,F0005,akhuni/axone,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Lactobacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
3,F0005,akhuni/axone,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Weissella_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
4,F0005,akhuni/axone,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Bacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
5,F0006,anishi,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",species,Anishi (fermented yam leaves),"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
6,F0009,bacillus spp.,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus spp.,"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
7,F0014,chinese douchi,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus subtilis,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
8,F0019,fermented bamboo shoots,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus subtilis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
9,F0019,fermented bamboo shoots,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus nepalensis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
10,F0019,fermented bamboo shoots,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
11,F0020,fermented fish products,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus subtilis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
12,F0020,fermented fish products,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus nepalensis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
13,F0023,fermented pork products,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus spp.,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
14,F0026,fish paste,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_S. cerevisiae,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
15,F0031,hawaijar,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
16,F0031,hawaijar,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Acetobacter,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
17,F0033,hentak,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
18,F0033,hentak,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
19,F0034,hilsa,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Puntius sophore,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
20,F0037,inziangsang,"[Northeast_India_c00003_ce27a60c, Northeast_In...",species,Lactobacillus plantarum,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00003_ce27a60c...
21,F0037,inziangsang,[Northeast_India_c00010_24a2beee],species,Pediococcus acidilactici,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
22,F0048,kimchi,[Ethnic_fermentation_secrets_of_Northeast_Indi...,species,_Leuconostoc_,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
23,F0048,kimchi,[Ethnic_fermentation_secrets_of_Northeast_Indi...,species,_Lactobacillus_,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
24,F0048,kimchi,[Ethnic_fermentation_secrets_of_Northeast_Indi...,species,_Weissella_,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
25,F0050,koong-som,[Chemical_and_microbial_properties_of_shidal_a...,species,Aspergillus oryzae,"{'status': 'verified_with_derived_fields', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
26,F0051,korean fermented fish jeot-gal,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus subtilis,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
27,F0052,lung seij,"[BambooShootinourBlood_c00003_3d8cb56a, Bamboo...",species,lung seij,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00003_3d...
28,F0053,miso,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Leuconostoc_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
29,F0053,miso,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Lactobacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
30,F0053,miso,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Weissella_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
31,F0056,myul-chi-jeot-gal,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus subtilis,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
32,F0056,myul-chi-jeot-gal,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus amyloliquefaciens,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
33,F0056,myul-chi-jeot-gal,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus sp. KA38,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
34,F0059,natto,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Aspergillus,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
35,F0059,natto,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus subtilis,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
36,F0061,ngari,[Chemical_and_microbial_properties_of_shidal_a...,genus,Staphylococcus,"{'status': 'verified_exact_or_normalized', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
37,F0061,ngari,[Chemical_and_microbial_properties_of_shidal_a...,genus,Micrococcus,"{'status': 'verified_exact_or_normalized', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
38,F0061,ngari,[Chemical_and_microbial_properties_of_shidal_a...,genus,Bacillus,"{'status': 'verified_exact_or_normalized', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
39,F0061,ngari,[Traditional_preparation_of_Na_kam_su_a_-_an_e...,species,_Satipinna phasa_,"{'status': 'verified_exact_or_normalized', 'fi...",Traditional preparation of Na kam su.a - an et...,[{'chunk_id': 'Traditional_preparation_of_Na_k...
40,F0062,ngawum,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,ngawum,"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
41,F0063,rice beer probiotics,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus subtilis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
42,F0063,rice beer probiotics,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus nepalensis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
43,F0063,rice beer probiotics,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
44,F0065,salami,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_S. cerevisiae,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
45,F0068,shedal,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,Bacillus spp.,"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
46,F0069,shidal,[Chemical_and_microbial_properties_of_shidal_a...,species,Setipinna phasa,"{'status': 'verified_with_derived_fields', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
47,F0071,soidon,"[BambooShootinourBlood_c00003_3d8cb56a, Bamboo...",species,soidon,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00003_3d...
48,F0073,squid miso,[Chemical_and_microbial_properties_of_shidal_a...,species,Aspergillus oryzae,"{'status': 'verified_with_derived_fields', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
49,F0076,traditional sausages,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_S. cerevisiae,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
50,F0078,tungtap,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,Bacillus spp.,"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
51,F0079,utonga-kupsu,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
52,F0079,utonga-kupsu,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
53,F0082,ziang dui,[Northeast_India_c00010_24a2beee],genus,Lactobacillus,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
54,F0082,ziang dui,[Northeast_India_c00010_24a2beee],genus,Pediococcus,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
55,F0083,ziang sang,[Northeast_India_c00010_24a2beee],genus,Lactobacillus,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
56,F0083,ziang sang,[Northeast_India_c00010_24a2beee],genus,Pediococcus,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...

In [26]:
t6['taxonomy_level'].value_counts()

taxonomy_level
genus      32
species    22
Name: count, dtype: int64

In [27]:
t6['taxonomy_name'].value_counts()

taxonomy_name
Bacillus spp.                    4
Bacillus subtilis                4
_S. cerevisiae                   3
_Lactobacillus_                  3
_Weissella_                      3
_Bacillus_                       3
_Bacillus subtilis_              3
_Staphylococcus nepalensis_      3
_Leuconostoc_                    3
_Bacillus                        3
_Staphylococcus                  2
Aspergillus oryzae               2
Pediococcus                      2
Lactobacillus                    2
soidon                           1
Setipinna phasa                  1
Staphylococcus                   1
ngawum                           1
_Satipinna phasa_                1
Bacillus                         1
Micrococcus                      1
axone                            1
_Aspergillus                     1
Bacillus sp. KA38                1
Bacillus amyloliquefaciens       1
lung seij                        1
Pediococcus acidilactici         1
Puntius sophore                  1
_Acetobacter                     1
Anishi (fermented yam leaves)    1
Lactobacillus plantarum          1
Name: count, dtype: int64

In [28]:
t6[t6['taxonomy_level'] == 'genus']

,food_id,food_name,evidence_chunk_ids,taxonomy_level,taxonomy_name,evidence_verification,source_pdf,evidence
1,F0005,akhuni/axone,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Leuconostoc_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
2,F0005,akhuni/axone,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Lactobacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
3,F0005,akhuni/axone,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Weissella_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
4,F0005,akhuni/axone,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Bacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
8,F0019,fermented bamboo shoots,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus subtilis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
9,F0019,fermented bamboo shoots,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus nepalensis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
10,F0019,fermented bamboo shoots,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
11,F0020,fermented fish products,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus subtilis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
12,F0020,fermented fish products,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus nepalensis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
14,F0026,fish paste,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_S. cerevisiae,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
15,F0031,hawaijar,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
16,F0031,hawaijar,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Acetobacter,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
17,F0033,hentak,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
18,F0033,hentak,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
28,F0053,miso,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Leuconostoc_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
29,F0053,miso,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Lactobacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
30,F0053,miso,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Weissella_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
34,F0059,natto,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Aspergillus,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
36,F0061,ngari,[Chemical_and_microbial_properties_of_shidal_a...,genus,Staphylococcus,"{'status': 'verified_exact_or_normalized', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
37,F0061,ngari,[Chemical_and_microbial_properties_of_shidal_a...,genus,Micrococcus,"{'status': 'verified_exact_or_normalized', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
38,F0061,ngari,[Chemical_and_microbial_properties_of_shidal_a...,genus,Bacillus,"{'status': 'verified_exact_or_normalized', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
41,F0063,rice beer probiotics,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus subtilis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
42,F0063,rice beer probiotics,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus nepalensis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
43,F0063,rice beer probiotics,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
44,F0065,salami,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_S. cerevisiae,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
49,F0076,traditional sausages,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_S. cerevisiae,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
51,F0079,utonga-kupsu,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
52,F0079,utonga-kupsu,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
53,F0082,ziang dui,[Northeast_India_c00010_24a2beee],genus,Lactobacillus,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
54,F0082,ziang dui,[Northeast_India_c00010_24a2beee],genus,Pediococcus,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
55,F0083,ziang sang,[Northeast_India_c00010_24a2beee],genus,Lactobacillus,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
56,F0083,ziang sang,[Northeast_India_c00010_24a2beee],genus,Pediococcus,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...

In [29]:
t6[
    (t6['taxonomy_level'] == 'species') &
    (t6['taxonomy_name'].str.split().str.len() == 1)
]

,food_id,food_name,evidence_chunk_ids,taxonomy_level,taxonomy_name,evidence_verification,source_pdf,evidence
0,F0005,akhuni/axone,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",species,axone,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
22,F0048,kimchi,[Ethnic_fermentation_secrets_of_Northeast_Indi...,species,_Leuconostoc_,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
23,F0048,kimchi,[Ethnic_fermentation_secrets_of_Northeast_Indi...,species,_Lactobacillus_,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
24,F0048,kimchi,[Ethnic_fermentation_secrets_of_Northeast_Indi...,species,_Weissella_,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
47,F0071,soidon,"[BambooShootinourBlood_c00003_3d8cb56a, Bamboo...",species,soidon,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00003_3d...

## **Table 7**

In [30]:
t7 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\tables\table7.json")
t7

,food_id,food_name,evidence_chunk_ids,microbe,count,evidence_verification,source_pdf,evidence
0,F0002,_namsing_,[Indigenous_fermented_foods_of_Northeast_India...,_Providencia,diverse bacterial genera,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
1,F0002,_namsing_,[Indigenous_fermented_foods_of_Northeast_India...,_Staphylococcus,diverse bacterial genera,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
2,F0004,akhuni (fermented soya beans),"[BambooShootinourBlood_c00014_ff4f1c86, Bamboo...",Sümi tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00014_ff...
3,F0006,anishi,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",Anishi (fermented yam leaves),None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
4,F0008,areca nut,[Ethnic_fermentation_secrets_of_Northeast_Indi...,LAB,naturally occurring sugars in the areca nut ar...,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
...,...,...,...,...,...,...,...,...
77,F0082,ziang dui,[Northeast_India_c00010_24a2beee],L. brevis,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
78,F0082,ziang dui,[Northeast_India_c00010_24a2beee],Pediococcus acidilactici,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
79,F0083,ziang sang,[Northeast_India_c00010_24a2beee],Lactobacillus plantarum,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
80,F0083,ziang sang,[Northeast_India_c00010_24a2beee],L. brevis,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
81,F0083,ziang sang,[Northeast_India_c00010_24a2beee],Pediococcus acidilactici,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...

In [31]:
t7

,food_id,food_name,evidence_chunk_ids,microbe,count,evidence_verification,source_pdf,evidence
0,F0002,_namsing_,[Indigenous_fermented_foods_of_Northeast_India...,_Providencia,diverse bacterial genera,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
1,F0002,_namsing_,[Indigenous_fermented_foods_of_Northeast_India...,_Staphylococcus,diverse bacterial genera,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
2,F0004,akhuni (fermented soya beans),"[BambooShootinourBlood_c00014_ff4f1c86, Bamboo...",Sümi tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00014_ff...
3,F0006,anishi,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",Anishi (fermented yam leaves),None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
4,F0008,areca nut,[Ethnic_fermentation_secrets_of_Northeast_Indi...,LAB,naturally occurring sugars in the areca nut ar...,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
...,...,...,...,...,...,...,...,...
77,F0082,ziang dui,[Northeast_India_c00010_24a2beee],L. brevis,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
78,F0082,ziang dui,[Northeast_India_c00010_24a2beee],Pediococcus acidilactici,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
79,F0083,ziang sang,[Northeast_India_c00010_24a2beee],Lactobacillus plantarum,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
80,F0083,ziang sang,[Northeast_India_c00010_24a2beee],L. brevis,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
81,F0083,ziang sang,[Northeast_India_c00010_24a2beee],Pediococcus acidilactici,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...

# **Verified**

In [32]:
t1 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\verification\verified\table1.json")
t1

,food_id,food_name,category,type,ethnic_group,source_pdf,source_pdfs,evidence,conflicts,evidence_verification,evidence_chunk_ids
0,F0001,_lactobacillus spicheri_ g2,Fermented Vegetable,Solid Fermented Food,None,Indigenous fermented foods of Northeast India ...,[Indigenous fermented foods of Northeast India...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...,[],"{'status': 'verified_with_derived_fields', 'fi...",[Indigenous_fermented_foods_of_Northeast_India...
1,F0002,_namsing_,Fermented Fish,Solid Fermented Food,Mising community of Assam,Indigenous fermented foods of Northeast India ...,[Indigenous fermented foods of Northeast India...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...,[],"{'status': 'verified_with_derived_fields', 'fi...",[Indigenous_fermented_foods_of_Northeast_India...
2,F0003,african or european traditional cultured milks,Fermented Dairy,Liquid Fermented Food,Northeast India,Ethnic fermentation secrets of Northeast India...,[Ethnic fermentation secrets of Northeast Indi...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...,[],"{'status': 'verified_with_derived_fields', 'fi...",[Ethnic_fermentation_secrets_of_Northeast_Indi...
3,F0004,akhuni (fermented soya beans),Fermented Vegetable,Solid Fermented Food,Sümi tribe,BambooShootinourBlood.pdf,[BambooShootinourBlood.pdf],[{'chunk_id': 'BambooShootinourBlood_c00014_ff...,[],"{'status': 'verified_with_derived_fields', 'fi...","[BambooShootinourBlood_c00014_ff4f1c86, Bamboo..."
4,F0005,akhuni/axone,Fermented Vegetable,Solid Fermented Food,Naga,BambooShootinourBlood.pdf,"[BambooShootinourBlood.pdf, Ethnic fermentatio...",[{'chunk_id': 'BambooShootinourBlood_c00012_1d...,"[{'field': 'ethnic_group', 'existing': 'Naga',...","{'status': 'verified_with_derived_fields', 'fi...","[BambooShootinourBlood_c00012_1dafbfa6, Bamboo..."
...,...,...,...,...,...,...,...,...,...,...,...
77,F0079,utonga-kupsu,Fermented Fish,Solid Fermented Food,None,Indigenous fermented foods of Northeast India ...,[Indigenous fermented foods of Northeast India...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...,[],"{'status': 'verified_with_derived_fields', 'fi...",[Indigenous_fermented_foods_of_Northeast_India...
78,F0080,wet/pulp/smoked,Fermented Vegetable,Solid Fermented Food,Naga,BambooShootinourBlood.pdf,[BambooShootinourBlood.pdf],[{'chunk_id': 'BambooShootinourBlood_c00012_1d...,[],"{'status': 'verified_with_derived_fields', 'fi...","[BambooShootinourBlood_c00012_1dafbfa6, Bamboo..."
79,F0081,zao,Fermented Beverage,Liquid Fermented Food,None,Metagenomic insights into traditional fermenta...,[Metagenomic insights into traditional ferment...,[{'chunk_id': 'Metagenomic_insights_into_tradi...,[],"{'status': 'verified_with_derived_fields', 'fi...",[Metagenomic_insights_into_traditional_ferment...
80,F0082,ziang dui,Fermented Vegetable,Solid Fermented Food,None,Northeast India.pdf,[Northeast India.pdf],[{'chunk_id': 'Northeast_India_c00010_24a2beee...,[],"{'status': 'verified_with_derived_fields', 'fi...","[Northeast_India_c00010_24a2beee, Northeast_In..."
81,F0083,ziang sang,Fermented Vegetable,Solid Fermented Food,None,Northeast India.pdf,[Northeast India.pdf],[{'chunk_id': 'Northeast_India_c00010_24a2beee...,[],"{'status': 'verified_with_derived_fields', 'fi...","[Northeast_India_c00010_24a2beee, Northeast_In..."

In [33]:
t2 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\verification\verified\table2.json")
t2

,food_id,food_name,evidence_chunk_ids,raw_material,amount,preparation_method,evidence_verification,source_pdf,evidence
0,F0002,_namsing_,[Indigenous_fermented_foods_of_Northeast_India...,_Namsing_,NaN,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
1,F0003,african or european traditional cultured milks,[Ethnic_fermentation_secrets_of_Northeast_Indi...,LAByeast consortia or kefir grains,NaN,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
2,F0003,african or european traditional cultured milks,[Ethnic_fermentation_secrets_of_Northeast_Indi...,defined inoculum of _B. subtilis_ var. _natto_,NaN,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
3,F0004,akhuni (fermented soya beans),"[BambooShootinourBlood_c00014_ff4f1c86, Bamboo...",tender bamboo shoot,NaN,chopped and sealed in assigned jars,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00014_ff...
4,F0004,akhuni (fermented soya beans),[BambooShootinourBlood_c00022_3bb1b36f],akhuni (fermented soya beans),NaN,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00022_3b...
...,...,...,...,...,...,...,...,...,...
84,F0076,traditional sausages,[Ethnic_fermentation_secrets_of_Northeast_Indi...,rice-based fermented beverages,NaN,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
85,F0077,tungrymbai,[Indigenous_fermented_foods_of_Northeast_India...,Tungrymbai,NaN,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
86,F0078,tungtap,[Indigenous_fermented_foods_of_Northeast_India...,Tungtap,NaN,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
87,F0078,tungtap,[Microbial_and_endogenous_origin_of_fibrinolyt...,phabou (P. sophore),NaN,"used for the production of ngari, shedal, tung...","{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
88,F0080,wet/pulp/smoked,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",fermented bamboo shoot (wet/pulp/smoked),NaN,any fresh bamboo shoot chopped and stored in a...,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...

In [36]:
t3 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\verification\verified\table3.json")
t3

,food_id,food_name,evidence_chunk_ids,state,district,ethnic_group,village,evidence_verification,source_pdf,evidence
0,F0002,_namsing_,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,Mising community of Assam,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
1,F0004,akhuni (fermented soya beans),"[BambooShootinourBlood_c00014_ff4f1c86, Bamboo...",None,NaN,Sümi tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00014_ff...
2,F0005,akhuni/axone,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Naga,Dimapur,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
3,F0006,anishi,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Khasis,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
4,F0006,anishi,[Northeast_India_c00003_ce27a60c],None,NaN,Northeast Indian women,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00003_ce27a60c...
5,F0010,baiya nigu,"[BambooShootinourBlood_c00028_5d7bb136, Bamboo...",None,NaN,Lotha Naga community,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00028_5d...
6,F0011,bamboo shoot,"[BambooShootinourBlood_c00005_7e25a3da, Bamboo...",None,NaN,Naga,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00005_7e...
7,F0012,barman community,"[BambooShootinourBlood_c00018_881965e5, Bamboo...",None,NaN,Barman community,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00018_88...
8,F0013,cheese,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
9,F0021,fermented foods,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
10,F0022,fermented mustard seeds,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Khasis,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
11,F0025,fermented yam leaves,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Khasis,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
12,F0025,fermented yam leaves,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Naga,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
13,F0026,fish paste,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,tribal communities of Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
14,F0027,fish sauce,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,tribal communities of Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
15,F0032,hentaak,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,Garo tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
16,F0037,inziangsang,"[Northeast_India_c00003_ce27a60c, Northeast_In...",None,NaN,Naga,Manipur and Nagaland,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00003_ce27a60c...
17,F0039,japanese shiokara,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,NaN,Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
18,F0040,judima,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,Dimasa Kachari community,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
19,F0040,judima,[Metagenomic_insights_into_traditional_ferment...,None,NaN,Dimasa Kachari,Judima,"{'status': 'verified_exact_or_normalized', 'fi...",Metagenomic insights into traditional fermenta...,[{'chunk_id': 'Metagenomic_insights_into_tradi...
20,F0041,kahudi/panitenga,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Khasis,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
21,F0044,khalpi,[Northeast_India_c00003_ce27a60c],None,NaN,Northeast Indian women,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00003_ce27a60c...
22,F0045,kharoli,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",None,NaN,Khasis,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
23,F0048,kimchi,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
24,F0049,kombucha,[BambooShootinourBlood_c00023_b6a2b5b8],New Delhi,NaN,None,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00023_b6...
25,F0049,kombucha,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
26,F0054,moinapara,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,None,Moinapara village,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
27,F0054,moinapara,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,Karbi community,Kuki household in Karbi Anglong,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
28,F0055,mustard seeds,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,Assam and the surrounding Northeastern states,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
29,F0057,na.kam su.a,[Traditional_preparation_of_Na_kam_su_a_-_an_e...,None,NaN,Garo tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",Traditional preparation of Na kam su.a - an et...,[{'chunk_id': 'Traditional_preparation_of_Na_k...
30,F0058,naga,"[BambooShootinourBlood_c00028_5d7bb136, Bamboo...",None,NaN,Lotha Naga community,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00028_5d...
31,F0061,ngari,[Chemical_and_microbial_properties_of_shidal_a...,None,NaN,Manipur,None,"{'status': 'verified_exact_or_normalized', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
32,F0061,ngari,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,Garo tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
33,F0061,ngari,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,NaN,None,Ngari (fermented fish product of Manipur),"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
34,F0061,ngari,[Traditional_preparation_of_Na_kam_su_a_-_an_e...,None,NaN,Garo tribes,None,"{'status': 'verified_exact_or_normalized', 'fi...",Traditional preparation of Na kam su.a - an et...,[{'chunk_id': 'Traditional_preparation_of_Na_k...
35,F0065,salami,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,tribal communities of Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
36,F0067,seedal,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,Garo tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
37,F0067,seedal,[Indigenous_fermented_foods_of_Northeast_India...,Arunachal Pradesh,NaN,None,Manipur,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
38,F0068,shedal,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,NaN,None,Phabou (P. sophore),"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
39,F0069,shidal,[Chemical_and_microbial_properties_of_shidal_a...,None,NaN,Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
40,F0069,shidal,[Indigenous_fermented_foods_of_Northeast_India...,None,NaN,Garo tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
41,F0070,sinki,[Northeast_India_c00003_ce27a60c],None,NaN,Northeast Indian women,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00003_ce27a60c...
42,F0071,soidon,[Indigenous_fermented_foods_of_Northeast_India...,Nagaland,NaN,Naga,None,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
43,F0072,soya beans,"[BambooShootinourBlood_c00005_7e25a3da, Bamboo...",None,NaN,Lotha Naga tribe of Nagaland,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00005_7e...
44,F0075,thap,[Metagenomic_insights_into_traditional_ferment...,None,NaN,Karbi tribes,Hor Alank,"{'status': 'verified_exact_or_normalized', 'fi...",Metagenomic insights into traditional fermenta...,[{'chunk_id': 'Metagenomic_insights_into_tradi...
45,F0075,thap,[Metagenomic_insights_into_traditional_ferment...,None,NaN,Tea tribes,Haria,"{'status': 'verified_exact_or_normalized', 'fi...",Metagenomic insights into traditional fermenta...,[{'chunk_id': 'Metagenomic_insights_into_tradi...
46,F0076,traditional sausages,[Ethnic_fermentation_secrets_of_Northeast_Indi...,None,NaN,tribal communities of Northeast India,None,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
47,F0078,tungtap,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,NaN,None,Tungtap,"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
48,F0082,ziang dui,[Northeast_India_c00010_24a2beee],None,NaN,Naga women,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
49,F0083,ziang sang,[Northeast_India_c00010_24a2beee],None,NaN,Naga women,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...

In [38]:
t4 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\verification\verified\table4.json")
t4

,food_id,food_name,evidence_chunk_ids,category,parameter,value,unit,evidence_verification,source_pdf,evidence
0,F0018,fermented bamboo shoot,"[BambooShootinourBlood_c00015_57ed4e30, Bamboo...",Proximate Composition,sour,strong,,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00015_57...
1,F0018,fermented bamboo shoot,[BambooShootinourBlood_c00015_57ed4e30],Proximate Composition,sweetness,strong,,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00015_57...
2,F0018,fermented bamboo shoot,[BambooShootinourBlood_c00015_57ed4e30],Proximate Composition,sour,way too strong for me,,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00015_57...
3,F0057,na.kam su.a,[Traditional_preparation_of_Na_kam_su_a_-_an_e...,Proximate Composition,moisture content,36.82%,None,"{'status': 'verified_with_derived_fields', 'fi...",Traditional preparation of Na kam su.a - an et...,[{'chunk_id': 'Traditional_preparation_of_Na_k...

In [39]:
t5 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\verification\verified\table5.json")
t5.head()

Empty DataFrame
Columns: []
Index: []

In [40]:
t6 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\verification\verified\table6.json")
t6

,food_id,food_name,evidence_chunk_ids,taxonomy_level,taxonomy_name,evidence_verification,source_pdf,evidence
0,F0005,akhuni/axone,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",species,axone,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
1,F0005,akhuni/axone,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Leuconostoc_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
2,F0005,akhuni/axone,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Lactobacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
3,F0005,akhuni/axone,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Weissella_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
4,F0005,akhuni/axone,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Bacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
5,F0006,anishi,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",species,Anishi (fermented yam leaves),"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
6,F0009,bacillus spp.,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus spp.,"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
7,F0014,chinese douchi,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus subtilis,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
8,F0019,fermented bamboo shoots,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus subtilis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
9,F0019,fermented bamboo shoots,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus nepalensis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
10,F0019,fermented bamboo shoots,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
11,F0020,fermented fish products,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus subtilis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
12,F0020,fermented fish products,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus nepalensis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
13,F0023,fermented pork products,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus spp.,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
14,F0026,fish paste,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_S. cerevisiae,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
15,F0031,hawaijar,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
16,F0031,hawaijar,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Acetobacter,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
17,F0033,hentak,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
18,F0033,hentak,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
19,F0034,hilsa,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Puntius sophore,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
20,F0037,inziangsang,"[Northeast_India_c00003_ce27a60c, Northeast_In...",species,Lactobacillus plantarum,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00003_ce27a60c...
21,F0037,inziangsang,[Northeast_India_c00010_24a2beee],species,Pediococcus acidilactici,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
22,F0048,kimchi,[Ethnic_fermentation_secrets_of_Northeast_Indi...,species,_Leuconostoc_,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
23,F0048,kimchi,[Ethnic_fermentation_secrets_of_Northeast_Indi...,species,_Lactobacillus_,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
24,F0048,kimchi,[Ethnic_fermentation_secrets_of_Northeast_Indi...,species,_Weissella_,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
25,F0050,koong-som,[Chemical_and_microbial_properties_of_shidal_a...,species,Aspergillus oryzae,"{'status': 'verified_with_derived_fields', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
26,F0051,korean fermented fish jeot-gal,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus subtilis,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
27,F0052,lung seij,"[BambooShootinourBlood_c00003_3d8cb56a, Bamboo...",species,lung seij,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00003_3d...
28,F0053,miso,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Leuconostoc_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
29,F0053,miso,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Lactobacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
30,F0053,miso,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Weissella_,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
31,F0056,myul-chi-jeot-gal,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus subtilis,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
32,F0056,myul-chi-jeot-gal,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus amyloliquefaciens,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
33,F0056,myul-chi-jeot-gal,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus sp. KA38,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
34,F0059,natto,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_Aspergillus,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
35,F0059,natto,[Microbial_and_endogenous_origin_of_fibrinolyt...,species,Bacillus subtilis,"{'status': 'verified_with_derived_fields', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
36,F0061,ngari,[Chemical_and_microbial_properties_of_shidal_a...,genus,Staphylococcus,"{'status': 'verified_exact_or_normalized', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
37,F0061,ngari,[Chemical_and_microbial_properties_of_shidal_a...,genus,Micrococcus,"{'status': 'verified_exact_or_normalized', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
38,F0061,ngari,[Chemical_and_microbial_properties_of_shidal_a...,genus,Bacillus,"{'status': 'verified_exact_or_normalized', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
39,F0061,ngari,[Traditional_preparation_of_Na_kam_su_a_-_an_e...,species,_Satipinna phasa_,"{'status': 'verified_exact_or_normalized', 'fi...",Traditional preparation of Na kam su.a - an et...,[{'chunk_id': 'Traditional_preparation_of_Na_k...
40,F0062,ngawum,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,ngawum,"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
41,F0063,rice beer probiotics,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus subtilis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
42,F0063,rice beer probiotics,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus nepalensis_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
43,F0063,rice beer probiotics,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus_,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
44,F0065,salami,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_S. cerevisiae,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
45,F0068,shedal,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,Bacillus spp.,"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
46,F0069,shidal,[Chemical_and_microbial_properties_of_shidal_a...,species,Setipinna phasa,"{'status': 'verified_with_derived_fields', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
47,F0071,soidon,"[BambooShootinourBlood_c00003_3d8cb56a, Bamboo...",species,soidon,"{'status': 'verified_with_derived_fields', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00003_3d...
48,F0073,squid miso,[Chemical_and_microbial_properties_of_shidal_a...,species,Aspergillus oryzae,"{'status': 'verified_with_derived_fields', 'fi...",Chemical and microbial properties of shidal a ...,[{'chunk_id': 'Chemical_and_microbial_properti...
49,F0076,traditional sausages,[Ethnic_fermentation_secrets_of_Northeast_Indi...,genus,_S. cerevisiae,"{'status': 'verified_with_derived_fields', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
50,F0078,tungtap,[Microbial_and_endogenous_origin_of_fibrinolyt...,None,Bacillus spp.,"{'status': 'verified_exact_or_normalized', 'fi...",Microbial and endogenous origin of fibrinolyti...,[{'chunk_id': 'Microbial_and_endogenous_origin...
51,F0079,utonga-kupsu,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Bacillus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
52,F0079,utonga-kupsu,[Indigenous_fermented_foods_of_Northeast_India...,genus,_Staphylococcus,"{'status': 'verified_with_derived_fields', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
53,F0082,ziang dui,[Northeast_India_c00010_24a2beee],genus,Lactobacillus,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
54,F0082,ziang dui,[Northeast_India_c00010_24a2beee],genus,Pediococcus,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
55,F0083,ziang sang,[Northeast_India_c00010_24a2beee],genus,Lactobacillus,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
56,F0083,ziang sang,[Northeast_India_c00010_24a2beee],genus,Pediococcus,"{'status': 'verified_with_derived_fields', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...

In [41]:
t7 = pd.read_json(r"E:\HILLUL\Project Associate - I\SDEP\ubuntu_logs\10 pdfs\data\verification\verified\table7.json")
t7

,food_id,food_name,evidence_chunk_ids,microbe,count,evidence_verification,source_pdf,evidence
0,F0002,_namsing_,[Indigenous_fermented_foods_of_Northeast_India...,_Providencia,diverse bacterial genera,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
1,F0002,_namsing_,[Indigenous_fermented_foods_of_Northeast_India...,_Staphylococcus,diverse bacterial genera,"{'status': 'verified_exact_or_normalized', 'fi...",Indigenous fermented foods of Northeast India ...,[{'chunk_id': 'Indigenous_fermented_foods_of_N...
2,F0004,akhuni (fermented soya beans),"[BambooShootinourBlood_c00014_ff4f1c86, Bamboo...",Sümi tribe,None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00014_ff...
3,F0006,anishi,"[BambooShootinourBlood_c00012_1dafbfa6, Bamboo...",Anishi (fermented yam leaves),None,"{'status': 'verified_exact_or_normalized', 'fi...",BambooShootinourBlood.pdf,[{'chunk_id': 'BambooShootinourBlood_c00012_1d...
4,F0008,areca nut,[Ethnic_fermentation_secrets_of_Northeast_Indi...,LAB,naturally occurring sugars in the areca nut ar...,"{'status': 'verified_exact_or_normalized', 'fi...",Ethnic fermentation secrets of Northeast India...,[{'chunk_id': 'Ethnic_fermentation_secrets_of_...
...,...,...,...,...,...,...,...,...
77,F0082,ziang dui,[Northeast_India_c00010_24a2beee],L. brevis,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
78,F0082,ziang dui,[Northeast_India_c00010_24a2beee],Pediococcus acidilactici,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
79,F0083,ziang sang,[Northeast_India_c00010_24a2beee],Lactobacillus plantarum,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
80,F0083,ziang sang,[Northeast_India_c00010_24a2beee],L. brevis,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...
81,F0083,ziang sang,[Northeast_India_c00010_24a2beee],Pediococcus acidilactici,None,"{'status': 'verified_exact_or_normalized', 'fi...",Northeast India.pdf,[{'chunk_id': 'Northeast_India_c00010_24a2beee...