In [8]:
import json
import pandas as pd

## **Food Id name Mapping**

In [4]:
food_ids_path = r'E:\HILLUL\Project Associate - I\SDEP\scientific-document-extraction-pipeline\data\tables\food_ids.json'

with open(food_ids_path, "r", encoding="utf-8") as f:
    data = json.load(f)

In [5]:
data[:3]

[{'food_id': 'F0001', 'food_name': 'aakhone', 'aliases': ['aakhone']},
 {'food_id': 'F0002', 'food_name': 'axone', 'aliases': ['axone']},
 {'food_id': 'F0003', 'food_name': 'behmi', 'aliases': ['behmi']}]

In [7]:
len(data)

72

In [10]:
food_ids_df = pd.DataFrame(data)
food_ids_df

   food_id   food_name       aliases
0    F0001     aakhone     [aakhone]
1    F0002       axone       [axone]
2    F0003       behmi       [behmi]
3    F0004      bekang      [bekang]
4    F0005    bhatooru    [bhatooru]
..     ...         ...           ...
67   F0068        sura        [sura]
68   F0069     tarhana     [tarhana]
69   F0070  tungrymbai  [tungrymbai]
70   F0071     tungtap     [tungtap]
71   F0072       zutho       [zutho]

[72 rows x 3 columns]

## **Table 1**

In [11]:
t1 = pd.read_json(r'E:\HILLUL\Project Associate - I\SDEP\scientific-document-extraction-pipeline\data\tables\table1.json')
t1

,food_id,food_name,category,type,ethnic_group,source_pdf,source_pdfs,evidence,conflicts
0,F0001,aakhone,Fermented Vegetable,Solid Fermented Food,"Sema Naga, Apatani tribes",Fermented food products in the Himalayan belt ...,[Fermented food products in the Himalayan belt...,[{'chunk_id': 'Fermented_food_products_in_the_...,[]
1,F0002,axone,Fermented Vegetable,Solid Fermented Food,"Sema Naga, Apatani tribes, Meitei, Khasi and Garo",Fermented food products in the Himalayan belt ...,[Fermented food products in the Himalayan belt...,[{'chunk_id': 'Fermented_food_products_in_the_...,[]
2,F0003,behmi,Fermented Vegetable,Solid Fermented Food,Nepal and ethnic communities in the Himalayan ...,Fermented food products in the Himalayan belt ...,[Fermented food products in the Himalayan belt...,[{'chunk_id': 'Fermented_food_products_in_the_...,[]
3,F0004,bekang,Fermented Vegetable,Solid Fermented Food,Mizo (Naga),Fermented food products in the Himalayan belt ...,[Fermented food products in the Himalayan belt...,[{'chunk_id': 'Fermented_food_products_in_the_...,[]
4,F0005,bhatooru,Fermented Vegetable,Solid Fermented Food,Nepali/Gorkha,Fermented food products in the Himalayan belt ...,[Fermented food products in the Himalayan belt...,[{'chunk_id': 'Fermented_food_products_in_the_...,[]
...,...,...,...,...,...,...,...,...,...
67,F0068,sura,Fermented Beverage,Alcoholic Fermented Beverage,Nepal,Fermented food products in the Himalayan belt ...,[Fermented food products in the Himalayan belt...,[{'chunk_id': 'Fermented_food_products_in_the_...,[]
68,F0069,tarhana,Fermented Vegetable,Solid Fermented Food,Nepali/Gorkha,Fermented food products in the Himalayan belt ...,[Fermented food products in the Himalayan belt...,[{'chunk_id': 'Fermented_food_products_in_the_...,[]
69,F0070,tungrymbai,Fermented Vegetable,Solid Fermented Food,Khasi and Garo in Meghalaya,Fermented food products in the Himalayan belt ...,[Fermented food products in the Himalayan belt...,[{'chunk_id': 'Fermented_food_products_in_the_...,[]
70,F0071,tungtap,Fermented Fish,Solid Fermented Food,Khasi in Meghalaya,Fermented food products in the Himalayan belt ...,[Fermented food products in the Himalayan belt...,[{'chunk_id': 'Fermented_food_products_in_the_...,[]
71,F0072,zutho,Fermented Dairy,Liquid Fermented Food,"Nepali/Gorkha, Bhutia, Tibetans, Dukpa and Lad...",Fermented food products in the Himalayan belt ...,[Fermented food products in the Himalayan belt...,[{'chunk_id': 'Fermented_food_products_in_the_...,[]

In [12]:
t1['category'].value_counts()

category
Fermented Vegetable                43
Fermented Beverage                  9
Fermented Dairy                     9
Fermented Fish                      4
Fermented Grain Beverage            2
Fermented Soybean                   1
Fermented Meat and Sea Products     1
Name: count, dtype: int64

In [13]:
t1['type'].value_counts()

type
Solid Fermented Food                53
Liquid Fermented Food                8
Non-alcoholic Fermented Beverage     6
Alcoholic Fermented Beverage         2
Name: count, dtype: int64

In [17]:
ethnic_group_col_val = t1['ethnic_group'].to_list()
ethnic_group_col_val = [ e.split(',') for e in ethnic_group_col_val]
ethnic_group = []

for e in ethnic_group_col_val:
    ethnic_group.extend(e)
ethnic_group = [ e.strip() for e in ethnic_group ]
ethnic_group,len(ethnic_group)

(['Sema Naga',
  'Apatani tribes',
  'Sema Naga',
  'Apatani tribes',
  'Meitei',
  'Khasi and Garo',
  'Nepal and ethnic communities in the Himalayan belt of Northeast India',
  'including Himachal Pradesh tribes',
  'Mizo (Naga)',
  'Nepali/Gorkha',
  'Nepal',
  'Bhutia',
  'Tibetans',
  'Dukpa and Ladakhi',
  'Nepali/Gorkha',
  'Bhutia',
  'Tibetans',
  'Dukpa and Ladakhi',
  'Nepali/Gorkha',
  'Bhutia',
  'Tibetans',
  'Dukpa and Ladakhi',
  'Nepal',
  'Himachal Pradesh (Himadri)',
  'Nepali/Gorkha',
  'Bhutia',
  'Tibetans',
  'Dukpa and Ladakhi',
  'Hindu',
  'Buddhist majority populace of the Himalayan region',
  'Nepali/Gorkha',
  'Bhutia',
  'Tibetans',
  'Dukpa and Ladakhi',
  'Ladakh',
  'Jaintia tribe (Pnar or Synteng)',
  'Assamese community',
  'Nepali/Gorkha',
  'Himachal rural population',
  'Ladakh',
  'Jaintia tribe (Pnar or Synteng)',
  'Assamese community',
  'Nepali/Gorkha',
  'Himachal population',
  'Sikkim and Nepal',
  'Nepal',
  'Himachal Pradesh (Himadri)',
  'Nepali',
  'Bhutanese',
  'Sikkimese',
  'and Himalayan tribes (including Uchoi and Jamatia)',
  'Meitei (Manipur)',
  'Khasi and Garo (Meghalaya)',
  'Apatanitribes (Ziro district of Arunachal Pradesh)',
  'Apatanitribes (Ziro district of Arunachal Pradesh)',
  'Meitei community Manipur',
  'Debbarma of Tripura',
  'Chakma and Uchoi tribes of Tripura',
  'Apatanitribes of Arunachal Pradesh',
  'Nepali/Gorkha',
  'Nagaland and Manipur people',
  'Nepali/Gorkha',
  'Nepal',
  'Uttaranchal (also known as Uttar Pradesh)',
  'Judima (Himalayan belt',
  'North East India)',
  'Meera Ongmu Bhutia',
  'Debbarma',
  'Chakma',
  'Uchoi tribes of Tripura',
  'and indigenous communities in Sikkim',
  'Ladakh',
  'Tibet',
  'Arunachal Pradesh',
  'and Bhutan',
  'Nepal',
  'Sikkim',
  'Bhutan',
  'and Himalayan regions of India (including Tripura)',
  'Apatani tribes in Arunachal Pradesh',
  'Sema Naga in Nagaland',
  'Assamese community',
  'Jaintia tribe (also known as Pnar or Synteng)',
  'Jaintia tribe (also known as Pnar or Synteng)',
  'Himalayas (specifically the region where gundruk is indigenous)',
  'Nepal',
  'Darjeeling hills',
  'Sikkim',
  'and south Bhutan',
  'Nepal',
  'Indo Mongoloids',
  'Tibeto-Burmese',
  'and proto-Austro-Asiatic tribes',
  'Meitei community',
  'Debbarma',
  'Chakma and Uchoi tribes of Tripura',
  'Apatanitribes (Arunachal Pradesh)',
  'Nepali/Gorkha community',
  'Nepali/Gorkha community',
  'Nepali/Gorkha community',
  'Nepali/Gorkha community',
  'Nepal and ethnic communities in the Himalayan belt of Northeast India',
  'including Himachal Pradesh tribes',
  'Nepal',
  'Uchoi',
  'Jamatia tribes and other tribes of Tripura',
  'Manipur people',
  'Apatani tribes in Arunachal Pradesh',
  'Bhutia',
  'Tibetans',
  'Dukpa and Ladakhi',
  'Ladakh (Jaintia)',
  'Ladakh',
  'Jaintia tribe (Pnar or Synteng)',
  'Assamese community',
  'Nepali/Gorkha',
  'Himachal rural population',
  'Ladakh',
  'Jaintia tribe (Pnar or Synteng)',
  'Putharo (commonly known as Putharai or Kharu in some regions)',
  'Nepal',
  'Nepali/Gorkha',
  'Himalayas (including North East India)',
  'Nepal',
  'more than 60 castes',
  'Nepali/Gorkha',
  'Nepal',
  'more than 60 castes in Nepal',
  'Indo Mongoloids',
  'Tibeto-Burmese',
  'and proto-Austrioloids',
  'Nepal',
  'more than 60 castes',
  'Uchoi and Jamatia tribes',
  'AmlaiNtoi',
  'Bikang',
  'Bochumba',
  'Kosoi tribes',
  'Ziang Sang',
  'Tapyo tribes of Tripura and Manipur-Arunach Pradesh',
  'Tripura',
  'Sikkim',
  'Bhutan',
  'Manipur',
  'Arunachal Pradesh',
  'Meghalaya',
  'Apatanitribes',
  'Meitei community of Manipur',
  'Manipuri',
  'Uchoi',
  'Jamatia tribes of Tripura and Apatani tribe of Arunachal Pradesh',
  'Ladakh',
  'Jaintia tribe (Pnar or Synteng)',
  'Japan',
  'Nepal',
  'Nepali/Gorkha',
  'Khasi and Garo in Meghalaya',
  'Khasi in Meghalaya',
  'Nepali/Gorkha',
  'Bhutia',
  'Tibetans',
  'Dukpa and Ladakhi'],
 162)

In [18]:
ethnic_group_set = set(ethnic_group)
ethnic_group_set,len(ethnic_group_set)

({'AmlaiNtoi',
  'Apatani tribes',
  'Apatani tribes in Arunachal Pradesh',
  'Apatanitribes',
  'Apatanitribes (Arunachal Pradesh)',
  'Apatanitribes (Ziro district of Arunachal Pradesh)',
  'Apatanitribes of Arunachal Pradesh',
  'Arunachal Pradesh',
  'Assamese community',
  'Bhutan',
  'Bhutanese',
  'Bhutia',
  'Bikang',
  'Bochumba',
  'Buddhist majority populace of the Himalayan region',
  'Chakma',
  'Chakma and Uchoi tribes of Tripura',
  'Darjeeling hills',
  'Debbarma',
  'Debbarma of Tripura',
  'Dukpa and Ladakhi',
  'Himachal Pradesh (Himadri)',
  'Himachal population',
  'Himachal rural population',
  'Himalayas (including North East India)',
  'Himalayas (specifically the region where gundruk is indigenous)',
  'Hindu',
  'Indo Mongoloids',
  'Jaintia tribe (Pnar or Synteng)',
  'Jaintia tribe (also known as Pnar or Synteng)',
  'Jamatia tribes and other tribes of Tripura',
  'Jamatia tribes of Tripura and Apatani tribe of Arunachal Pradesh',
  'Japan',
  'Judima (Himalayan belt',
  'Khasi and Garo',
  'Khasi and Garo (Meghalaya)',
  'Khasi and Garo in Meghalaya',
  'Khasi in Meghalaya',
  'Kosoi tribes',
  'Ladakh',
  'Ladakh (Jaintia)',
  'Manipur',
  'Manipur people',
  'Manipuri',
  'Meera Ongmu Bhutia',
  'Meghalaya',
  'Meitei',
  'Meitei (Manipur)',
  'Meitei community',
  'Meitei community Manipur',
  'Meitei community of Manipur',
  'Mizo (Naga)',
  'Nagaland and Manipur people',
  'Nepal',
  'Nepal and ethnic communities in the Himalayan belt of Northeast India',
  'Nepali',
  'Nepali/Gorkha',
  'Nepali/Gorkha community',
  'North East India)',
  'Putharo (commonly known as Putharai or Kharu in some regions)',
  'Sema Naga',
  'Sema Naga in Nagaland',
  'Sikkim',
  'Sikkim and Nepal',
  'Sikkimese',
  'Tapyo tribes of Tripura and Manipur-Arunach Pradesh',
  'Tibet',
  'Tibetans',
  'Tibeto-Burmese',
  'Tripura',
  'Uchoi',
  'Uchoi and Jamatia tribes',
  'Uchoi tribes of Tripura',
  'Uttaranchal (also known as Uttar Pradesh)',
  'Ziang Sang',
  'and Bhutan',
  'and Himalayan regions of India (including Tripura)',
  'and Himalayan tribes (including Uchoi and Jamatia)',
  'and indigenous communities in Sikkim',
  'and proto-Austrioloids',
  'and proto-Austro-Asiatic tribes',
  'and south Bhutan',
  'including Himachal Pradesh tribes',
  'more than 60 castes',
  'more than 60 castes in Nepal'},
 85)

## **Table 2**

In [19]:
t2 = pd.read_json(r'E:\HILLUL\Project Associate - I\SDEP\scientific-document-extraction-pipeline\data\tables\table2.json')
t2

,food_id,food_name,evidence_chunk_ids,raw_material,amount,preparation_method,source_pdf,evidence
0,F0001,aakhone,[Fermented_food_products_in_the_Himalayan_belt...,soybean,NaN,grown under rain-fed conditions in upland terr...,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
1,F0001,aakhone,[Fermented_food_products_in_the_Himalayan_belt...,soybean,NaN,cooked for 2-3 h until the beans become soft. ...,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
2,F0003,behmi,[Fermented_food_products_in_the_Himalayan_belt...,behmi,NaN,fermented,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
3,F0004,bekang,[Fermented_food_products_in_the_Himalayan_belt...,soybean,NaN,grown under rain-fed conditions in upland terr...,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
4,F0004,bekang,[Fermented_food_products_in_the_Himalayan_belt...,soybean seeds,NaN,"collected, cleaned, soaked in water for 10–12 ...",Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
...,...,...,...,...,...,...,...,...
133,F0070,tungrymbai,[Fermented_food_products_in_the_Himalayan_belt...,soybean,NaN,grown under rain-fed conditions in upland terr...,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
134,F0070,tungrymbai,[Fermented_food_products_in_the_Himalayan_belt...,soybean,NaN,"collected, cleaned, soaked in water for 10–12 ...",Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
135,F0071,tungtap,[Fermented_food_products_in_the_Himalayan_belt...,sun-dried fish (Danio spp.),NaN,washed briefly and mixed with salt. The sun-dr...,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
136,F0071,tungtap,[Fermented_food_products_in_the_Himalayan_belt...,"_L. lactis_ subsp. _cremoris, L. plantarum, E....",NaN,None,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
137,F0071,tungtap,[Fermented_food_products_in_the_Himalayan_belt...,_Candida and Saccharomycopsis,NaN,None,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...

In [20]:
t2['raw_material'].value_counts()

raw_material
Bamboo shoots                    12
soybean                           8
rice, barley or finger millet     7
yak milk                          4
mustard seeds                     3
                                 ..
Cucumis sativus L.                1
fish                              1
bamboo shoots                     1
meat (yak/beef/pork)              1
_Candida and Saccharomycopsis     1
Name: count, Length: 99, dtype: int64

## **Table 3**

In [21]:
t3 = pd.read_json(r'E:\HILLUL\Project Associate - I\SDEP\scientific-document-extraction-pipeline\data\tables\table3.json')
t3

,food_id,food_name,evidence_chunk_ids,state,district,ethnic_group,village,source_pdf,evidence
0,F0001,aakhone,[Fermented_food_products_in_the_Himalayan_belt...,None,None,Sema Naga,None,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
1,F0002,axone,[Fermented_food_products_in_the_Himalayan_belt...,None,None,"Sema Naga, Apatani tribes",None,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
2,F0003,behmi,[Fermented_food_products_in_the_Himalayan_belt...,None,None,Nepal,None,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
3,F0004,bekang,[Fermented_food_products_in_the_Himalayan_belt...,None,None,Mizo,Mizoram,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
4,F0004,bekang,[Fermented_food_products_in_the_Himalayan_belt...,None,None,Naga,Nagaland,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
...,...,...,...,...,...,...,...,...,...
56,F0064,soidon,[Fermented_food_products_in_the_Himalayan_belt...,None,None,Meitei community Manipur,None,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
57,F0068,sura,[Fermented_food_products_in_the_Himalayan_belt...,None,None,Nepal,None,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
58,F0070,tungrymbai,[Fermented_food_products_in_the_Himalayan_belt...,None,None,Khasi and Garo,Meghalaya,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
59,F0071,tungtap,[Fermented_food_products_in_the_Himalayan_belt...,None,None,Khasi,None,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
60,F0072,zutho,[Fermented_food_products_in_the_Himalayan_belt...,None,None,Rabha tribe,None,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...

In [25]:
t3['state'].value_counts()

state
Sikkim       1
Meghalaya    1
Name: count, dtype: int64

In [26]:
t3['district'].value_counts()

district
Sikkim                                1
Ziro                                  1
Ziro district of Arunachal Pradesh    1
Ziro district, Arunachal Pradesh      1
Name: count, dtype: int64

In [27]:
t3['ethnic_group'].value_counts()

ethnic_group
Nepali/Gorkha                                            11
Nepal                                                    10
Meitei community Manipur                                  3
Bhutia, Tibetans, Dukpa and Ladakhi                       3
Jaintia tribe (also known as Pnar or Synteng)             3
Nepali/Gorkha community                                   2
Apatanitribes                                             2
Sema Naga                                                 1
Darjeeling hills and Sikkim ethnic people                 1
Manipuri people                                           1
Apatani tribes in Arunachal Pradesh                       1
Jaintia tribe                                             1
Himachal Pradesh                                          1
Jaintia                                                   1
Assamese community                                        1
Uchoi and Jamatia tribes                                  1
Khasi and Garo                                            1
Khasi                                                     1
Nepali community in the Eastern Himalayas                 1
Jaintia hills of the state of Meghalaya                   1
Leh – Ladakh region of Jammu and Kashmir State, India     1
Brahmin Nepalis                                           1
Sema Naga, Apatani tribes                                 1
Himachal                                                  1
Uttarakhand, Kashmir and Ladakh                           1
Nagaland and Manipur                                      1
Meitei                                                    1
Himachali people                                          1
Nepali/Gorkha, Bhutia, Tibetans, Dukpa and Ladakhi        1
Naga                                                      1
Mizo                                                      1
Rabha tribe                                               1
Name: count, dtype: int64

In [28]:
t3['village'].value_counts()

village
Jaintia hills of the state of Meghalaya    5
Mizoram                                    1
Nagaland                                   1
Sikkim                                     1
Rural population of Himachal               1
Meghalaya                                  1
Name: count, dtype: int64

## **Table 4: Nutrition**

In [30]:
t4 = pd.read_json(r'E:\HILLUL\Project Associate - I\SDEP\scientific-document-extraction-pipeline\data\tables\table4.json')
t4

,food_id,food_name,evidence_chunk_ids,category,parameter,value,unit,source_pdf,evidence
0,F0001,aakhone,[Fermented_food_products_in_the_Himalayan_belt...,Proximate Composition,Water (%),64.9 ± 1.2,%,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
1,F0001,aakhone,[Fermented_food_products_in_the_Himalayan_belt...,Proximate Composition,Crude Protein (%),24.6 ± 0.9,%,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
2,F0001,aakhone,[Fermented_food_products_in_the_Himalayan_belt...,Proximate Composition,Crude Fat (%),4.6 ± 0.3,%,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
3,F0001,aakhone,[Fermented_food_products_in_the_Himalayan_belt...,Proximate Composition,Ash (%),4.9 ± 0.2,%,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
4,F0001,aakhone,[Fermented_food_products_in_the_Himalayan_belt...,Proximate Composition,Moisture (%),6.4 ± 0.2,%,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
...,...,...,...,...,...,...,...,...,...
288,F0072,zutho,[Fermented_food_products_in_the_Himalayan_belt...,Proximate Composition,Ash,2.5%,%,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
289,F0072,zutho,[Fermented_food_products_in_the_Himalayan_belt...,Proximate Composition,Moisture,75%,%,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
290,F0072,zutho,[Fermented_food_products_in_the_Himalayan_belt...,Proximate Composition,Crude Protein,2.5%,%,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
291,F0072,zutho,[Fermented_food_products_in_the_Himalayan_belt...,Proximate Composition,Crude Fat,2.5%,%,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
292,F0072,zutho,[Fermented_food_products_in_the_Himalayan_belt...,Proximate Composition,Crude Fiber,2.5%,%,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...

In [31]:
t4['category'].value_counts()

category
Proximate Composition    293
Name: count, dtype: int64

In [32]:
t4['parameter'].value_counts()

parameter
Ash                       40
Energy Composition        39
Crude Protein             35
Crude Fat                 33
Crude Fiber               31
Moisture                  30
Mineral Composition        9
Water (%)                  7
Crude Fat (%)              7
Ash (%)                    7
Vitamin Composition        6
Crude Protein (%)          6
Crude Fiber (%)            6
Amino Acid Composition     6
Crude protein              4
Fatty Acid Composition     3
Moisture (%)               2
Crude fat                  2
Crude fiber                2
Total lipids               2
Moisture content           2
Total Lipid                1
total lipids               1
crude protein              1
Yeast                      1
Bacteria                   1
Total Carbohydrate         1
Total Solids               1
Protein                    1
Ash content                1
dietary fiber content      1
carbohydrate content       1
potassium content          1
fat content                1
Alcohol content            1
Name: count, dtype: int64

## **Table 5**

In [34]:
t5 = pd.read_json(r'E:\HILLUL\Project Associate - I\SDEP\scientific-document-extraction-pipeline\data\tables\table5.json')
t5.head()

,food_id,entity_type,entity_name,moisture,ash,protein,fat,fiber,carbohydrate,source_pdf,evidence_chunk_ids,evidence
0,F0003,food,behmi,75% %,2.5% %,None,NaN,NaN,NaN,Fermented food products in the Himalayan belt ...,[Fermented_food_products_in_the_Himalayan_belt...,[{'chunk_id': 'Fermented_food_products_in_the_...
1,F0004,food,bekang,9.4% %,0.6% %,None,NaN,NaN,NaN,Fermented food products in the Himalayan belt ...,[Fermented_food_products_in_the_Himalayan_belt...,[{'chunk_id': 'Fermented_food_products_in_the_...
2,F0005,food,bhatooru,62.4% %,2.4% %,None,NaN,NaN,NaN,Fermented food products in the Himalayan belt ...,[Fermented_food_products_in_the_Himalayan_belt...,[{'chunk_id': 'Fermented_food_products_in_the_...
3,F0006,food,chhang,85% %,1.5% %,None,NaN,NaN,NaN,Fermented food products in the Himalayan belt ...,[Fermented_food_products_in_the_Himalayan_belt...,[{'chunk_id': 'Fermented_food_products_in_the_...
4,F0007,food,chhu,82.5% %,2.5% %,None,NaN,NaN,NaN,Fermented food products in the Himalayan belt ...,[Fermented_food_products_in_the_Himalayan_belt...,[{'chunk_id': 'Fermented_food_products_in_the_...

In [35]:
t5['moisture'].value_counts()

moisture
85% %            4
82.5% %          3
13.5% %          3
75% %            2
8.5% %           2
85.5 g/100g %    2
net g/100g %     2
68.1% %          1
bytes            1
6.4% %           1
81.5 g/100g %    1
75.4 g/100g %    1
36.8% %          1
9.4% %           1
85.5% %          1
82% %            1
62.4% %          1
81% %            1
Name: count, dtype: int64

In [36]:
t5['ash'].value_counts()

ash
2.5% %                      7
1.5% %                      6
1.3% %                      4
0.6% %                      3
16.73% %                    2
net g/100g %                2
2.4 g/100g %                2
1.5 g/100g %                2
2.6 g/100g %                1
1.8 ± 0.3% %                1
net g/100g = 0.5 g g        1
2.5 g/100g %                1
1.4% %                      1
3.6% %                      1
2.4% %                      1
4.6% %                      1
bytes                       1
net g/100g = 0.4 g /100g    1
Name: count, dtype: int64

## **Table 6**

In [37]:
t6 = pd.read_json(r'E:\HILLUL\Project Associate - I\SDEP\scientific-document-extraction-pipeline\data\tables\table6.json')
t6

,food_id,food_name,evidence_chunk_ids,taxonomy_level,taxonomy_name,source_pdf,evidence
0,F0001,aakhone,[Fermented_food_products_in_the_Himalayan_belt...,species,Bacillus subtilis,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
1,F0002,axone,[Fermented_food_products_in_the_Himalayan_belt...,species,Glycine max L.,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
2,F0003,behmi,[Fermented_food_products_in_the_Himalayan_belt...,species,Mucor miehei,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
3,F0004,bekang,[Fermented_food_products_in_the_Himalayan_belt...,species,Bacillus subtilis,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
4,F0004,bekang,[Fermented_food_products_in_the_Himalayan_belt...,species,Bacillus licheniformis,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
...,...,...,...,...,...,...,...
165,F0072,zutho,[Fermented_food_products_in_the_Himalayan_belt...,species,Lactobacillus helveticus,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
166,F0072,zutho,[Fermented_food_products_in_the_Himalayan_belt...,species,Lactobacillus casei,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
167,F0072,zutho,[Fermented_food_products_in_the_Himalayan_belt...,species,Lactobacillus reuteri,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
168,F0072,zutho,[Fermented_food_products_in_the_Himalayan_belt...,species,Lactobacillus fermentum,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
169,F0072,zutho,[Fermented_food_products_in_the_Himalayan_belt...,species,Lactobacillus delbrueckii subsp. bulgaricus,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...

In [38]:
t6['taxonomy_level'].value_counts()

taxonomy_level
species    168
genus        2
Name: count, dtype: int64

In [39]:
t6['taxonomy_name'].value_counts()

taxonomy_name
_S. cerevisiae                                                                                                    10
Lactobacillus plantarum                                                                                           10
Mucor miehei                                                                                                       7
Lactobacillus brevis                                                                                               6
Leuconostoc fallax                                                                                                 6
                                                                                                                  ..
Kloeckera sp.                                                                                                      1
Pichia sp.                                                                                                         1
Candida sp.                                                                                                        1
Lb. sake, Lb. divergens, Lb. carnis, Lb. sanfransisco, Lb. curvatus, Leuc. mesenteroides, E. faecium, Bacillus     1
Lactobacillus delbrueckii subsp. bulgaricus                                                                        1
Name: count, Length: 77, dtype: int64

In [40]:
t6[t6['taxonomy_level'] == 'genus']

,food_id,food_name,evidence_chunk_ids,taxonomy_level,taxonomy_name,source_pdf,evidence
44,F0019,hawaijar,[Fermented_food_products_in_the_Himalayan_belt...,genus,Bacillus,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
45,F0019,hawaijar,[Fermented_food_products_in_the_Himalayan_belt...,genus,Glycine max,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...

In [46]:
t6[
    (t6['taxonomy_level'] == 'species') &
    (t6['taxonomy_name'].str.split().str.len() == 1)
]

,food_id,food_name,evidence_chunk_ids,taxonomy_level,taxonomy_name,source_pdf,evidence
63,F0024,inziangsang,[Fermented_food_products_in_the_Himalayan_belt...,species,_Pediococcus_,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...
108,F0038,lonailish,[Fermented_food_products_in_the_Himalayan_belt...,species,Tenualosailisha,Fermented food products in the Himalayan belt ...,[{'chunk_id': 'Fermented_food_products_in_the_...